nomeDoCliente = input("Digite o nome do Cliente: ")
diaDoVencimento = input("Digite o dia do vencimento: ")
mesDoVencimento = input("Digite o mês do vencimento: ")
valorDaFatura = input("Digite o valor da fatura: ")
print("Olá,", nomeDoCliente)
print("A sua fatura com vencimento em", diaDoVencimento, "de", mesDoVencimento, "no valor de R$", valorDaFatura, "está fechada.")
